name: Deploy to Minikube

on: [push]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Minikube
      uses: medyagh/setup-minikube@master

    - name: Build Docker image
      run: |
        eval $(minikube docker-env)
        docker build -t devopshint/node-app:latest .

    - name: Deploy to Kubernetes
      run: |
        kubectl apply -f k8s-node-app.yaml
        kubectl get all

    - name: Verify deployment
      run: |
        kubectl wait --for=condition=available deployment/nodejs-app --timeout=120s
        minikube service nodejs-app --url